version: 1
organization:
  org_id: maestro
  org_slug: maestro
  display_name: Maestro
defaults:
  port_stride: 20
  policy:
    integrations:
      allow:
        - telegram
        - whatsapp
        - discord
        - slack
        - signal
        - google-chat
        - irc
        - imessage
        - bluebubbles
        - webchat
        - mattermost
        - microsoft-teams
        - teams
        - feishu
        - lark
        - line
        - matrix
        - zalo
        - zalo-personal
        - nextcloud-talk
        - nostr
        - twitch
        - tlon
      deny: []
    skills:
      allow: []
      deny: []
      allow_sources:
        - bundled
        - managed
        - workspace
      deny_sources: []
    models:
      allow_providers:
        - openai
        - anthropic
        - openrouter
        - litellm
        - ollama
      deny_providers: []
      allow_models: []
      deny_models: []
instances:
  - id: core-human
    enabled: true
    profile: human
    host:
      bind: 127.0.0.1
      gateway_port: 19789
    paths:
      config_dir: ../instances/core-human/config
      state_dir: ../instances/core-human/state
      workspace_root: ../instances/core-human/workspaces
      generated_dir: ../.generated/core-human
    openclaw:
      config_layers:
        - ../templates/openclaw/org.base.json5
        - ../templates/openclaw/profiles/human.base.json5
        - ../instances/core-human/config/instance.overrides.json5
      docker:
        image: ghcr.io/openclaw/openclaw:latest
        container_name: openclaw-core-human
        restart: unless-stopped
    policy:
      integrations:
        allow:
          - telegram
      models:
        allow_providers:
          - openai
          - anthropic
    channels:
      telegram:
        accounts:
          vbarsegyan: {}
          drichardson: {}
    agents:
      - id: vbarsegyan
        role: human
        workspace: vbarsegyan
        agent_dir: agents/vbarsegyan
        model: openai/gpt-5-nano
        integrations:
          - telegram
        skills:
          - github
          - coding-agent
        skill_sources:
          - bundled
        bindings:
          - match:
              channel: telegram
              accountId: vbarsegyan
      - id: drichardson
        role: human
        workspace: drichardson
        agent_dir: agents/drichardson
        model: openai/gpt-5-nano
        integrations:
          - telegram
        skills:
          - github
        skill_sources:
          - bundled
        bindings:
          - match:
              channel: telegram
              accountId: drichardson